# Generated by Django 3.2.12 on 2022-11-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecar', '0002_movie_have_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
