# Generated by Django 3.2.12 on 2022-11-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviecar', '0003_auto_20221116_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.CharField(default='#', max_length=1024),
        ),
    ]
